pipelines:
 branches:
  master:
    - step:
        deployment: Production
        caches:
          - composer
        script:
          - pipe: atlassian/rsync-deploy:0.4.1
            variables:
              USER: $USER
              SERVER: $SERVER
              REMOTE_PATH: ''
              LOCAL_PATH: '.' 
              EXTRA_ARGS: '--exclude=uploads/* --exclude=.git --exclude=composer.json --exclude=composer.* --exclude=bitbucket-pipelines.yml'
